[customizations.installer.kickstart]
contents = """
lang en_US.UTF-8
keyboard --vckeymap=us-dvorak --xlayouts=dvorak
timezone America/New_York

user --name testuser --password test --plaintext --groups wheel
rootpw --lock

zerombr
clearpart --all --initlabel
autopart --type=btrfs
reboot --eject

%post
bootc switch --mutate-in-place --transport registry ghcr.io/setupminimal/hackberry:latest
%end
"""

